### ISSUE TITLE
Program does not terminate when running GraphSAGE sampling

### ISSUE THREAD

**Issue by yuejiewang** [plasma-umass/NextDoor#15]
Hi @abhijangda ,

When I run the khop sampling in src/apps/khop on reddit dataset, but modify the number of neighbors in each layer (step) to [25, 10] (the same config with GraphSAGE model), the program does not terminate. The command I ran (in NextDoor/src/app/khop) is:

make bin
./KHopSampling -g <path to reddit dataset> -t edge-list -f binary -n 1 -k TransitParallel -l -p

The output is like:
![a0ff4ea1e03cb0cede6e62e9abdefca](https://user-images.githubusercontent.com/61261975/134943677-46d153cb-5c5d-4f34-8c82-2dac992ed49c.png)
And then it won't proceed
Do you know what migh be the reason? Thanks!

**Comment by yuejiewang** [comment]
@marcoserafini @abhijangda I really appreciate it if you could help me with this problem. Thanks a lot!

**Comment by abhijangda** [comment]
Hi @yuejiewang, 

Can you post your system configuration including GPU and CUDA version, and the graph. 
I suspect it is because warp divergence is happening somewhere and warp sync is not used correctly.

Thank You

**Comment by yuejiewang** [comment]
Hi @abhijangda 

The GPU I used is NVIDIA Quadro RTX 8000, CUDA version 11.0, and the graph is reddit.data included in your paper.

Thank you!

**Comment by yuejiewang** [comment]
Hi @abhijangda ,

I just ran the same experiment on V100 and CUDA 11.2, which I believe is the same configuration as stated in your paper, but I encountered the same problem. I think maybe you would be interested in this new result. Thanks!

**Comment by abhijangda** [comment]
Pull Request https://github.com/plasma-umass/NextDoor/pull/18 fixes this issue.
